# Generated by Django 4.1.2 on 2022-10-12 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_universitario', models.CharField(max_length=30)),
                ('correo_institucional', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=30)),
                ('cedula_persona', models.PositiveIntegerField()),
                ('telefono_persona', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ruta', models.CharField(max_length=30)),
                ('estado_ruta', models.CharField(max_length=30)),
                ('recorrido_ruta', models.TextField()),
                ('Conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaza_dis', models.CharField(max_length=30)),
                ('horario_salida', models.CharField(max_length=30)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.estudiante')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.persona'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.persona'),
        ),
    ]
